apiRules:
- include:
    uidRegex: ^Joshf67
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- include:
    uidRegex: ^Example
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace